name: Release-test

on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest    
  steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
